version: '3.7'
  services: 

    vuejs:
    container_name: frontend
    image: mtommyp14/front:main
    ports:
      - 8080:8080
    environment:
      - VUE_APP_URL=http://52.87.205.126:9001/api/
    networks: 
      - devopsnet

networks: 
  devopsnet: